using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NeuroNexusBackend.Models
{

    /// <summary>
    /// A user-owned deck, composed of many DeckCard rows.
    /// </summary>
    [Table("Decks")]
    [Index(nameof(UserId))] // Speeds up queries "list decks by user"
    public class Deck
    {
        /// <summary>
        /// Primary key (UUID). Generated by the application.
        /// </summary>
        [Key]
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>
        /// Owner user id (FK). Required.
        /// </summary>
        [Required]
        public Guid UserId { get; set; }

        /// <summary>
        /// Optional navigation to the owner (not required for writes).
        /// </summary>
        public User? User { get; set; }

        /// <summary>
        /// Human-friendly deck name.
        /// </summary>
        [Required]
        [StringLength(64, MinimumLength = 1)]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Creation timestamp (UTC). Set once at insert time.
        /// </summary>
        [Required]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Collection of card entries (card + quantity) that make up the deck.
        /// </summary>
        public List<DeckCard> Cards { get; set; } = new();
    }

}
