using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NeuroNexusBackend.Models
{
    /// <summary>
    /// A georeferenced spawn on the map. It may optionally point to a Card.
    /// </summary>
    [Table("Spawns")]
    [Index(nameof(Status))]         // speeds up queries by status
    [Index(nameof(ExpiresAt))]      // speeds up TTL/cleanup queries
    public class Spawn
    {
        /// <summary>
        /// Primary key (UUID). Generated by the application.
        /// </summary>
        [Key]
        [Comment("Primary key for Spawns (UUID).")]
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>
        /// Geographic point (longitude, latitude) in SRID 4326.
        /// Note: SRID is enforced/configured in the DbContext (HasSrid(4326)).
        /// </summary>
        [Required]
        [Comment("Geographic point in WGS84 (SRID 4326): (lon, lat).")]
        public Point Location { get; set; } = default!;

        /// <summary>
        /// Optional link to a card to be granted/previewed at this spawn.
        /// </summary>
        [Comment("Optional foreign key to Cards.Id.")]
        public int? CardId { get; set; }

        /// <summary>
        /// Lifecycle state of the spawn. Constrained by regex.
        /// </summary>
        [Required]
        [RegularExpression("active|claimed|expired|caught")]
        [StringLength(16)]
        [Comment("Spawn status: active|claimed|expired|caught.")]
        public string Status { get; set; } = "active";

        /// <summary>
        /// Optional expiration timestamp (UTC). When reached, the spawn is no longer available.
        /// </summary>
        [Comment("Optional expiration timestamp in UTC.")]
        public DateTime? ExpiresAt { get; set; }

        /// <summary>
        /// Creation timestamp (UTC). Set once at insert time.
        /// </summary>
        [Required]
        [Comment("Creation timestamp in UTC.")]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
