namespace NeuroNexusBackend.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using Microsoft.EntityFrameworkCore;

    namespace NeuroNexus.Api.Models;

    /// <summary>
    /// Represents an account in the system. Users own decks and perform actions.
    /// </summary>
    [Table("Users")]
    [Index(nameof(Handle), IsUnique = true)] // Unique index to prevent duplicated handles
    public class User
    {
        /// <summary>
        /// Primary key (UUID). Generated by the application for simplicity.
        /// </summary>
        [Key]
        [Comment("Primary key for Users (UUID).")]
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>
        /// Public-facing nickname. Must be unique and short.
        /// </summary>
        [Required]
        [StringLength(32, MinimumLength = 3)]
        [DataType(DataType.Text)]
        [Comment("Unique handle/nickname for the user.")]
        public string Handle { get; set; } = default!;

        /// <summary>
        /// Creation timestamp (UTC). Set once at insert time.
        /// </summary>
        [Required]
        [Comment("Creation timestamp in UTC.")]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }

}
