using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NeuroNexusBackend.Models
{
   
    /// <summary>
    /// Represents an account in the system. Users own decks and perform actions.
    /// </summary>
    [Table("Users")]
    [Index(nameof(Handle), IsUnique = true)] // Unique index to prevent duplicated handles
    public class User
    {
        /// <summary>
        /// Primary key (UUID). Generated by the application for simplicity.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        /// <summary>
        /// Public-facing nickname. Must be unique and short.
        /// </summary>
        [Required]
        [StringLength(32, MinimumLength = 3)]
        [DataType(DataType.Text)]
        public string Handle { get; set; } = default!;

        /// <summary>
        /// Creation timestamp (UTC). Set once at insert time.
        /// </summary>
        [Required]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }

}
